#!/usr/bin/env python3
"""Rebuild docs/index.md from frontmatter and report broken wikilinks.

Usage: python3 scripts/build-index.py
Exit code 1 if any wikilink does not resolve, so it can gate a commit.
"""
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
FEATURES = DOCS / "features"
DECISIONS = DOCS / "decisions"
INDEX = DOCS / "index.md"

FM_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)
LINK_RE = re.compile(r"\[\[([^\]|#]+)")
CODE_RE = re.compile(r"```.*?```|`[^`\n]*`", re.S)  # links inside code are not links


def frontmatter(text):
    m = FM_RE.match(text)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.split("#", 1)[0].strip()
        fm[key.strip()] = value
    return fm


def title(text):
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return "(untitled)"


def collect(folder):
    rows = []
    for path in sorted(folder.glob("*.md")):
        text = path.read_text()
        fm = frontmatter(text)
        rows.append({
            "slug": path.stem,
            "id": fm.get("id", "?"),
            "status": fm.get("status", "?"),
            "updated": fm.get("updated") or fm.get("date", "?"),
            "title": title(text),
        })
    return sorted(rows, key=lambda r: r["id"])


def all_slugs():
    return {p.stem for p in DOCS.rglob("*.md")} | {p.stem for p in (ROOT / "_meta").glob("*.md")}


def broken_links():
    slugs = all_slugs()
    problems = []
    for path in list(DOCS.rglob("*.md")) + list((ROOT / "_meta").glob("*.md")):
        if path == INDEX:
            continue
        for target in LINK_RE.findall(CODE_RE.sub("", path.read_text())):
            if target.strip() not in slugs:
                problems.append((path.relative_to(ROOT), target))
    return problems


def table(rows, kind):
    out = [f"| {kind} | Id | Status | Updated |", "|---|---|---|---|"]
    for r in rows:
        out.append(f"| [{r['title']}]({kind.lower()}s/{r['slug']}.md) | {r['id']} | `{r['status']}` | {r['updated']} |")
    return "\n".join(out)


def main():
    features = collect(FEATURES)
    decisions = collect(DECISIONS)
    counts = {}
    for r in features:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    summary = ", ".join(f"{n} {s}" for s, n in sorted(counts.items()))

    body = "\n".join([
        "---",
        "type: index",
        f"generated: {date.today().isoformat()}",
        "---",
        "# Index",
        "",
        "GENERATED by `scripts/build-index.py`. Do not edit. Rebuild after any change under `docs/`.",
        "",
        f"Features: {summary}.",
        "",
        "## Features",
        "",
        table(features, "Feature"),
        "",
        "## Decisions",
        "",
        table(decisions, "Decision"),
        "",
    ])
    INDEX.write_text(body)
    print(f"wrote {INDEX.relative_to(ROOT)}: {len(features)} features, {len(decisions)} decisions")

    problems = broken_links()
    for path, target in problems:
        print(f"broken link in {path}: [[{target}]]")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
